---
- name: ansible playbook using variables which are passing from external file to the playbook
  hosts: all
  become: true
  vars_files:
    - user.yml
  tasks:
  - name: creating a user
    user:
      name: "{{ user }}"


