---
- name: ansible playbook using variables which are passing within the playbook
  hosts: all
  become: true
  vars: 
   user: modi 
  tasks:
  - name: creating a user
    user:
      name: "{{ user }}"

