---
- name: ansible palybook to test ansible vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
  - name: clone a repo
    git: 
      repo: https://eindu:{{ password }}@github.com/eindu/vault-1.git
      dest: /opt/ansadmin/test-vault
