---
- name: ansible playbook to copy index.html file to rhel and linux dest nodes
  hosts: all
  become: true
  tasks:
  - name: copying a file
    copy:
      src: /opt/ansible/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: john
